### ISSUE TITLE
feature: test that package can be used to `get_me` and `create_chunk`

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve-dotnet-client#3]

**Comment by vid277** [comment]
**Testing `get_me`:**
![318657720-67d98131-1e60-4e08-baf2-b91ddc61e434](https://github.com/devflowinc/trieve-dotnet-client/assets/74870683/0b237002-5bb0-42a0-a55c-2587b52913f1)

**Testing `create_chunk`:**
<img width="548" alt="image" src="https://github.com/devflowinc/trieve-dotnet-client/assets/74870683/24feff04-78af-4824-a55c-4302b8798c3b">
